import { Section } from './types';

export const INITIAL_SECTIONS: Section[] = [
  {
    id: 'header-1',
    type: 'header',
    name: 'Header (Menú)',
    content: {
      logoText: 'ACADEMY ENGLISH QUICK',
    },
    styles: {
      backgroundColor: '#0B3FA7',
      textColor: '#FFFFFF',
      accentColor: '#D60000',
      paddingY: 'py-4',
      fontSizeTitle: 'text-xl',
      fontSizeBody: 'text-base',
      textAlign: 'left',
    },
  },
  {
    id: 'hero-1',
    type: 'hero',
    name: 'Hero Section (Principal)',
    content: {
      title: 'Domina el Inglés Rápidamente',
      subtitle: 'La metodología más efectiva para impulsar tu futuro profesional. / The most effective methodology to boost your professional future.',
      imageUrl: 'https://picsum.photos/1200/800',
      imageBrightness: 70, // Default slightly darker for better text contrast
    },
    styles: {
      backgroundColor: '#0B3FA7',
      textColor: '#FFFFFF',
      accentColor: '#D60000',
      paddingY: 'py-20',
      fontSizeTitle: 'text-5xl',
      fontSizeBody: 'text-xl',
      textAlign: 'center',
    },
  },
  {
    id: 'why-us-1',
    type: 'why-us',
    name: '¿Por qué elegirnos?',
    content: {
      title: '¿Por qué elegirnos? / Why choose us?',
      description: 'Gozamos de un equipo de trabajo constituido por docentes especialistas en metodología pedagógica, preparados para identificar y optimizar tus inteligencias múltiples más desarrolladas, y enseñarte de manera eficaz y eficiente.\n\nEnglish Quick Virtual Academy\'s approach is specifically designed to support and lead our Latin American students, to understand, learn and perform the most common tasks in remote and in-person jobs, mainly in Canada, Europe and the US.',
      imageUrl: 'https://picsum.photos/600/400',
      imageBrightness: 100,
      features: [
        { title: 'Metodología Ágil', desc: 'Aprende en tiempo récord.' },
        { title: 'Certificación', desc: 'Validez internacional.' },
        { title: 'Horarios Flexibles', desc: 'Estudia a tu ritmo.' },
      ],
    },
    styles: {
      backgroundColor: '#F3F4F6',
      textColor: '#1F1F1F',
      accentColor: '#124FC4',
      paddingY: 'py-16',
      fontSizeTitle: 'text-3xl',
      fontSizeBody: 'text-lg',
      textAlign: 'left',
    },
  },
  {
    id: 'academic-1',
    type: 'academic',
    name: 'Enfoque Académico',
    content: {
      title: 'Enfoque Académico / Academic Focus',
      description: 'El enfoque de English Quick Academy está diseñado para favorecer actividades comunes del trabajo remoto, presencial y entrevistas con confianza en Canadá, Europa y Estados Unidos.\n\nRoles: Appointment setters, closers, team leaders, loyalty agents, cold callers, clerks, virtual assistants, programmers, developers, customer support.\n\nAdditionally, we provide workforce support to US, Canada and English-speaking countries in Europe to ace interviews with confidence. We linguistically prepare Latin American applicants to quickly develop sufficient English proficiency.',
      imageUrl: 'https://picsum.photos/600/401',
      imageBrightness: 100,
    },
    styles: {
      backgroundColor: '#FFFFFF',
      textColor: '#1F1F1F',
      accentColor: '#0B3FA7',
      paddingY: 'py-16',
      fontSizeTitle: 'text-3xl',
      fontSizeBody: 'text-lg',
      textAlign: 'left',
    },
  },
  {
    id: 'jobs-1',
    type: 'jobs',
    name: 'Áreas Laborales',
    content: {
      title: 'Áreas Laborales / Job Areas',
      description: 'Prepárate para los roles más demandados en el mercado internacional:',
      items: [
        { text: 'Appointment Setters' },
        { text: 'Closers' },
        { text: 'Team Leaders' },
        { text: 'Loyalty Agents' },
        { text: 'Cold Callers' },
        { text: 'Virtual Assistants' },
        { text: 'Programmers & Developers' },
        { text: 'Customer Support' },
      ],
    },
    styles: {
      backgroundColor: '#124FC4',
      textColor: '#FFFFFF',
      accentColor: '#D60000',
      paddingY: 'py-16',
      fontSizeTitle: 'text-3xl',
      fontSizeBody: 'text-lg',
      textAlign: 'center',
    },
  },
  {
    id: 'institutional-1',
    type: 'institutional',
    name: 'Institucional',
    content: {
      title: 'Nuestra Institución',
      description: 'Con más de 10 años formando líderes bilingües, contamos con instalaciones modernas y un equipo docente de primer nivel.\n\nCEO: JOHN POLO, Orlando FLA, Cali COL',
      imageUrl: 'https://picsum.photos/800/600',
      imageBrightness: 100,
      ceoImageUrl: '',
    },
    styles: {
      backgroundColor: '#FFFFFF',
      textColor: '#1F1F1F',
      accentColor: '#0B3FA7',
      paddingY: 'py-16',
      fontSizeTitle: 'text-3xl',
      fontSizeBody: 'text-lg',
      textAlign: 'left',
    },
  },
  {
    id: 'footer-1',
    type: 'footer',
    name: 'Pie de Página (Contacto)',
    content: {
      title: 'Contáctanos',
      subtitle: 'CEO: JOHN POLO, Orlando FLA, Cali COL',
      ceoImageUrl: '',
      socialLinks: {
        instagram: 'https://www.instagram.com/englishquickacademy/',
        facebook: 'https://www.facebook.com/english.quickacademy/?rdid=NW9qqh7WBArq5x4r',
        youtube: 'https://www.youtube.com/@englishquickacademy',
        tiktok: 'https://www.tiktok.com/@english.quickacad',
        whatsappLatam: '+57 3018130044',
        whatsappUS: '+1 (407)536-1473',
        linktree: 'https://linktr.ee/englishquick',
      },
    },
    styles: {
      backgroundColor: '#1F1F1F',
      textColor: '#FFFFFF',
      accentColor: '#D60000',
      paddingY: 'py-12',
      fontSizeTitle: 'text-xl',
      fontSizeBody: 'text-sm',
      textAlign: 'center',
    },
  },
];